test-project1:
- changed-files:
  - any-glob-to-any-file: 'services/test-project1/**/*'

test-project2:
- changed-files:
  - any-glob-to-any-file: 'services/test-project2/**/*'

test-project3:
- changed-files:
  - any-glob-to-any-file: 'services/test-project3/**/*'

test-project4:
- changed-files:
    - any-glob-to-any-file: 'services/test-project4/**/*'

test-project5:
  - changed-files:
      - any-glob-to-any-file: 'services/test-project5/**/*'