name: "Pull Request Actions"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  Run-Pull-Request-Actions:
    name: Run Pull Request Actions 
    runs-on: [self-hosted]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Add changed services labels to Pull Request"
        uses: actions/labeler@v5
        with:
          sync-labels: true
